# 第8章 异常

​	在编写程序的时候，程序员通常需要辨别事件的正常过程和异常情况。这类异常可能是错误（比如试图除以0），或者是不希望经常发生的事情。为了能够处理这些异常事件，可以在所有可能发生这类事件的地方都使用if语句。但是，这么做不仅会没效率和不灵活，而且还会让程序难以阅读。你可能会想直接忽略这些异常事件，希望它们永不发生。Python的异常对象提供了非常强大的替代解决方案。

​	本章中，我们将学习如何创建和引发自定义的异常，以及处理异常的各种方法。

## 8.1 什么是异常

Python用异常对象来表示异常情况。遇到错误后会引发异常。如果异常对象未被处理或捕捉，程序就会用所谓的回潮终止执行。

简言之：异常之后的代码就不执行了

```python
1/0
>>>
Traceback (most recent call last):
  File "C:/Users/qa/PycharmProjects/S6/面向对象/815练习.py", line 245, in <module>
    1/0
ZeroDivisionError: division by zero
```

事实上，每个异常都是一些类（本例中是ZeroDivisionError）的实例。这些实例可以被引发，并且可以用很多种方法进行捕捉，使得程序可以捉住错误并对其进行处理，而不是让整个程序失败。

## 8.2 按自己的方式出错

异常可以在某些东西出错时自动引发。在学习处理异常之前，先看一下自己如何引发异常——甚至创建自己的异常类型。

### 8.2.1 raise语句

可以使用一个异常类调用raise来引发异常，可以自定义添加错误信息

```python
raise NameError('我爱你') 
```

一些常见的内建异常类：

| 类名                | 描述                            |
| ----------------- | ----------------------------- |
| Exception         | 所有异常类的基类                      |
| AttributeError    | 特性引用或赋值失败时引发                  |
| IOError           | 试图打开不存在的文件时引发                 |
| IndexError        | 使用序列中不存在的索引时引发                |
| KeyError          | 使用映射中不存在的键时引发                 |
| NameError         | 找不到名字（变量名）时引发                 |
| SyntaxError       | 语法错误                          |
| TypeError         | 在函数应用于错误类型的对象时引发              |
| ValueError        | 在函数应用于正确类型的对象，但是该对象使用不合适的值时引发 |
| ZeroDivisionError | 在除法或求模时第二个参数为0时引发             |

### 8.2.2 自定义异常类

语法和定义普通类一样，只是要确保从BaseException类继承。

```python
class EgonException(BaseException):
    def __init__(self,msg):
        self.msg = msg

try:
    raise EgonException('egon一脸懵逼')
except EgonException as e:
    print(e)
```

## 8.3 捕捉异常

try + except

```python
try:
    1 / 0
except ZeroDivisionError:
    print('不能除以0')
```

## 8.4 不止一个except语句

一个try语句可以搭配多个except语句

```python
try:
    x
    1 / 0
except ZeroDivisionError:
    print('不能除以0')
except NameError:
    print('名字错误')
```

## 8.5 用一个块捕捉多个异常

将多个异常类放在元组中一起交给except

```python
try:
    # 1/0
    '1'/2
except (TypeError,ZeroDivisionError):
    print('typeWrong or zeroWrong')
```

## 8.6 起别名

在except语句中使用as

```python
try:
    1/0
except ZeroDivisionError as e:
    print(e)
```

## 8.7 全捕捉

在except子句中忽略所有的异常类。

```python
try:
    1/0
except: 
    print('something wrong is happend')
```

这样捕捉异常是危险的，因为它会隐藏我们未想到或没有做好准备处理的异常。这时候使用Exception as e会好一些，或者对对象e做一些检查。

```python
try:
    1/0
except Exception as e:
    print(e)
```

## 8.8 else子句

else代码块中的内容会在没有异常发生时执行，否则就不会执行。

```python
try:
    print('=' * 20)
    # num
except NameError as name_e: # 如果捕获了NameError，下面的代码就不会执行
    print(name_e)
else:
    print('没有捕捉到异常')
```

## 8.9 最后

finally与try搭配使用，无论如何都会执行

```python
try:
    print(11) # 异常发生前的代码正常执行
    1/0
    print(22)
except ZeroDivisionError as e:
    print(e)
finally:
    print(333)  # 无论如何都会执行

'''
11
division by zero
333
'''
```

## 8.10 异常和函数

异常和函数能很自然的一起工作。如果异常在函数内引发而不被处理，它会传播到函数调用的地方。如果在那里也没有被处理，它会继续传播，一直到达主程序（全局作用域）。如果在主程序中也没有异常处理程序，程序会带着堆栈跟踪终止。

```python
def faulty():
    raise Exception('Something is wrong')

def ignore_exception():
    faulty()

def handle_exception():
    try:
        faulty()
    except:
        print('Exception handled')
```

```python
ignore_exception() # 引发异常 Exception: Something is wrong
```

faulty中产生的异常通过faulty和ignore_exception传播，最终导致了堆栈跟踪。

```python
handle_exception() # Exception handled
```

传播到handle_exception时，被try/except语句处理。

## 8.11 异常之禅

异常处理并不是很复杂。如果知道某段代码会发生异常，却又不希望程序已堆栈跟踪的形式终止，那么就根据需要添加try/except/else/finally的组合进行处理。

有时候条件语句可以实现和异常处理同样的功能，只是在意外情况比较多时，条件语句在自然性和可读性方面差一些。

你能想到有异常，并且可能出现在这一块代码的异常有很多种，不能一一枚举时，异常处理比较适用。

很多情况下，使用try/except语句比使用if/else会更自然一些（更python化）。

try/except语句在Python中的的表现可以用一句妙语解释“请求宽恕易于请求许可”。在做一件事时去处理可能出现的错误，而不是在开始前就进行大量的检查，这个策略可以总结成习语“看前就跳（Leap Before You Look）。

## 8.12 小结

+ 异常对象。异常情况可以用异常对象表示。它们可以用几种方法处理，但是如果忽略的话，程序就会终止。
+ 警告。警告类似于异常，但是一般仅仅打印错误信息。
+ 引发异常。可以使用raise语句引发异常。它接收异常类或者异常实例作为参数，还可以起别名。
+ 自定义异常类。用继承BaseException类的方式可以创建自己的异常类。
+ 捕捉异常。使用try语句的except子句捕获异常。在except子句中可以指定一个异常类，多个异常类，或者不绑定异常类。
+ else子句。如果try代码块没有引发异常，就会执行else中的代码。
+ finally。finally块中的代码不管是否有异常引发都会执行。
+ 异常和函数。在函数内引发异常时，它会被传播到函数调用的地方。

### 8.12.1 本章的新函数

| 函数                                 | 描述     |
| ---------------------------------- | ------ |
| warnings.filterwarnings(action...) | 用于过滤警告 |

### 8.12.2 接下来学什么

接下来学习类的魔术方法